from .layer13_histogram_limit import (
    NODE_CLASS_MAPPINGS as HIST_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as HIST_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_scale_by_long_short_edge import (
    NODE_CLASS_MAPPINGS as SCALE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCALE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_video_from_vhs import (
    NODE_CLASS_MAPPINGS as VIDEO_FROM_VHS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_FROM_VHS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_multi_image_input import (
    NODE_CLASS_MAPPINGS as MULTI_IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_for_loop_index import (
    NODE_CLASS_MAPPINGS as FOR_LOOP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FOR_LOOP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_text_join_n import (
    NODE_CLASS_MAPPINGS as TEXT_JOIN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_JOIN_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_text_loader import (
    NODE_CLASS_MAPPINGS as TEXT_LOADER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_random_loader_n import (
    NODE_CLASS_MAPPINGS as RANDOM_LOADER_N_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RANDOM_LOADER_N_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_grid_split_to_batch import (
    NODE_CLASS_MAPPINGS as GRID_SPLIT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GRID_SPLIT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_grid_from_batch import (
    NODE_CLASS_MAPPINGS as GRID_FROM_BATCH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GRID_FROM_BATCH_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_image_batch_append import (
    NODE_CLASS_MAPPINGS as IMAGE_BATCH_APPEND_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_BATCH_APPEND_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_persistent_counter import (
    NODE_CLASS_MAPPINGS as PERSISTENT_COUNTER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PERSISTENT_COUNTER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_fullscreen_watermark import (
    NODE_CLASS_MAPPINGS as FULLSCREEN_WATERMARK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FULLSCREEN_WATERMARK_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_masked_exposure import (
    NODE_CLASS_MAPPINGS as MASKED_EXPOSURE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MASKED_EXPOSURE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_masked_color_match import (
    NODE_CLASS_MAPPINGS as MASKED_COLOR_MATCH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MASKED_COLOR_MATCH_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_real_pixel_texture import (
    NODE_CLASS_MAPPINGS as REAL_PIXEL_TEXTURE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REAL_PIXEL_TEXTURE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_image_compress import (
    NODE_CLASS_MAPPINGS as IMAGE_COMPRESS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_COMPRESS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_metadata_cleaner import (
    NODE_CLASS_MAPPINGS as METADATA_CLEANER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as METADATA_CLEANER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_phone_camera import (
    NODE_CLASS_MAPPINGS as PHONE_CAMERA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PHONE_CAMERA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_apimart import (
    NODE_CLASS_MAPPINGS as APIMART_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as APIMART_NODE_DISPLAY_NAME_MAPPINGS,
)

from . import layer13_load_image_default as _LAYER13_LOAD_IMAGE_DEFAULT
from .layer13_grok_prompt import (
    NODE_CLASS_MAPPINGS as GROK_PROMPT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GROK_PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)
from . import layer13_server as _LAYER13_SERVER

try:
    from .layer13_audio_tools import (
        NODE_CLASS_MAPPINGS as AUDIO_TOOLS_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as AUDIO_TOOLS_NODE_DISPLAY_NAME_MAPPINGS,
    )
except Exception as exc:
    AUDIO_TOOLS_NODE_CLASS_MAPPINGS = {}
    AUDIO_TOOLS_NODE_DISPLAY_NAME_MAPPINGS = {}
    print(f"[layer13] layer13_audio_tools disabled: {exc}")

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(HIST_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SCALE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_FROM_VHS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MULTI_IMAGE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FOR_LOOP_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_JOIN_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_LOADER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(RANDOM_LOADER_N_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GRID_SPLIT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GRID_FROM_BATCH_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_BATCH_APPEND_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PERSISTENT_COUNTER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FULLSCREEN_WATERMARK_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MASKED_EXPOSURE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MASKED_COLOR_MATCH_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(REAL_PIXEL_TEXTURE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_COMPRESS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(METADATA_CLEANER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PHONE_CAMERA_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(APIMART_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(AUDIO_TOOLS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GROK_PROMPT_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(HIST_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SCALE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_FROM_VHS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MULTI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FOR_LOOP_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_JOIN_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_LOADER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RANDOM_LOADER_N_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GRID_SPLIT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GRID_FROM_BATCH_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_BATCH_APPEND_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PERSISTENT_COUNTER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FULLSCREEN_WATERMARK_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASKED_EXPOSURE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASKED_COLOR_MATCH_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(REAL_PIXEL_TEXTURE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_COMPRESS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(METADATA_CLEANER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PHONE_CAMERA_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(APIMART_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_TOOLS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GROK_PROMPT_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
