from .layer13_histogram_limit import (
    NODE_CLASS_MAPPINGS as HIST_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as HIST_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_scale_by_long_short_edge import (
    NODE_CLASS_MAPPINGS as SCALE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCALE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_video_from_vhs import (
    NODE_CLASS_MAPPINGS as VIDEO_FROM_VHS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_FROM_VHS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_multi_image_input import (
    NODE_CLASS_MAPPINGS as MULTI_IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_for_loop_index import (
    NODE_CLASS_MAPPINGS as FOR_LOOP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FOR_LOOP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_text_join_n import (
    NODE_CLASS_MAPPINGS as TEXT_JOIN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_JOIN_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_random_loader_n import (
    NODE_CLASS_MAPPINGS as RANDOM_LOADER_N_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RANDOM_LOADER_N_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_grid_split_to_batch import (
    NODE_CLASS_MAPPINGS as GRID_SPLIT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GRID_SPLIT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .layer13_grid_from_batch import (
    NODE_CLASS_MAPPINGS as GRID_FROM_BATCH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GRID_FROM_BATCH_NODE_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(HIST_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SCALE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_FROM_VHS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MULTI_IMAGE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FOR_LOOP_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_JOIN_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(RANDOM_LOADER_N_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GRID_SPLIT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GRID_FROM_BATCH_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(HIST_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SCALE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_FROM_VHS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MULTI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FOR_LOOP_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_JOIN_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RANDOM_LOADER_N_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GRID_SPLIT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GRID_FROM_BATCH_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
